FROM node:18-alpine

# Set timezone
RUN apk add --no-cache tzdata

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the source code
COPY . .

# Build TypeScript
RUN npm run build

# Run the tests and start the application if tests pass
CMD ["sh", "-c", "npm test && node ./dist/ntp-client.js"]
